name: pyreleaser
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "fetch unshallow"
        run: git fetch --prune --unshallow
      - name: "list"
        run: pwd && ls -la
      - name: "deps"
        run: python -m pip install -r requirements/local.txt
      - name: "package"
        run: make package-source
      - name: "list"
        run: ls -la ./dist/
      - name: "release"
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*"
      # Via: https://github.com/actions/upload-release-asset/issues/60#issuecomment-755205520
      #
      # Create release, then upload using alexellis' action.
      #- name: "create release"
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: ${{ github.ref }}
      #- name: Upload Release Assets
      #  uses: alexellis/upload-assets@0.4.1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    asset_paths: '["./dist/*"]'
